# version: "3"
services:
    nginx:
        image: stinfo-front:prod
        labels:
          - dev.orbstack.domains=stinfo-front.orb.local
        container_name: stinfo-front
        ports: 
          - "9999:9999"
        volumes:
          - /Users/phillip/Desktop/stinfo/front-end_nginx_conf/logs:/var/log/nginx
          - /Users/phillip/Desktop/stinfo/front-end_nginx_conf/nginx.conf:/etc/nginx/nginx.conf
          - /Users/phillip/Desktop/stinfo/front-end_nginx_conf/sites-enabled:/etc/nginx/sites-enabled
        environment:
          - TZ=Asia/Taipei
    